<?php
return [
	1 => ['id' => 1, 'name' => 'PORTUARIA', 'rp_id' => '1.1'],
	2 => ['id' => 2, 'name' => 'CENTRO', 'rp_id' => '1.1'],
	3 => ['id' => 3, 'name' => 'RIO COMPRIDO', 'rp_id' => '1.1'],
	7 => ['id' => 7, 'name' => 'SAO CRISTOVAO', 'rp_id' => '1.1'],
	21 => ['id' => 21, 'name' => 'PAQUETA', 'rp_id' => '1.1'],
	23 => ['id' => 23, 'name' => 'SANTA TEREZA', 'rp_id' => '1.1'],
	4 => ['id' => 4, 'name' => 'BOTAFOGO', 'rp_id' => '2.1'],
	5 => ['id' => 5, 'name' => 'COPACABANA', 'rp_id' => '2.1'],
	6 => ['id' => 6, 'name' => 'LAGOA', 'rp_id' => '2.1'],
	8 => ['id' => 8, 'name' => 'TIJUCA', 'rp_id' => '2.2'],
	9 => ['id' => 9, 'name' => 'VILA ISABEL', 'rp_id' => '2.2'],
	10 => ['id' => 10, 'name' => 'RAMOS', 'rp_id' => '3.1'],
	11 => ['id' => 11, 'name' => 'PENHA', 'rp_id' => '3.5'],
	31 => ['id' => 31, 'name' => 'VIGARIO GERAL', 'rp_id' => '3.5'],
	12 => ['id' => 12, 'name' => 'INHAUMA', 'rp_id' => '3.4'],
	13 => ['id' => 13, 'name' => 'MEIER', 'rp_id' => '3.2'],
	14 => ['id' => 14, 'name' => 'IRAJA', 'rp_id' => '3.3'],
	15 => ['id' => 15, 'name' => 'MADUREIRA', 'rp_id' => '3.3'],
	20 => ['id' => 20, 'name' => 'ILHA DO GOVERNADOR', 'rp_id' => '3.7'],
	22 => ['id' => 22, 'name' => 'ANCHIETA', 'rp_id' => '3.6'],
	25 => ['id' => 25, 'name' => 'PAVUNA', 'rp_id' => '3.6'],
	16 => ['id' => 16, 'name' => 'JACAREPAGUA', 'rp_id' => '4.1'],
	34 => ['id' => 34, 'name' => 'CIDADE DE DEUS', 'rp_id' => '4.1'],
	24 => ['id' => 24, 'name' => 'BARRA DA TIJUCA', 'rp_id' => '4.2'],
	33 => ['id' => 33, 'name' => 'REALENGO', 'rp_id' => '5.1'],
	17 => ['id' => 17, 'name' => 'BANGU', 'rp_id' => '5.1'],
	18 => ['id' => 18, 'name' => 'CAMPO GRANDE', 'rp_id' => '5.2'],
	19 => ['id' => 19, 'name' => 'SANTA CRUZ', 'rp_id' => '5.3'],
	26 => ['id' => 26, 'name' => 'GUARATIBA', 'rp_id' => '5.4'],
	27 => ['id' => 27, 'name' => 'ROCINHA', 'rp_id' => '2.1'],
	28 => ['id' => 28, 'name' => 'JACAREZINHO', 'rp_id' => '3.2'],
	29 => ['id' => 29, 'name' => 'COMPLEXO DO ALEMÃO', 'rp_id' => '3.4'],
	30 => ['id' => 30, 'name' => 'COMPLEXO DA MARE', 'rp_id' => '3.1'],
];