<?php
return [
	['code' => 'CGM', 'name' => 'Controladoria Geral do Município'],
	['code' => 'GBP', 'name' => 'Gabinete do Prefeito'],
	['code' => 'PGM', 'name' => 'Procuradoria Geral do Município'],
	['code' => 'CVL', 'name' => 'Secretaria Municipal da Casa Civil'],
	['code' => 'SMASDH', 'name' => 'Secretaria Municipal de Assistência Social e Direitos Humanos'],
	['code' => 'SECONSERMA', 'name' => 'Secretaria Municipal de Conservação e Meio Ambiente'],
	['code' => 'SMC', 'name' => 'Secretaria Municipal de Cultura'],
	['code' => 'SMDEI', 'name' => 'Secretaria Municipal de Desenvolvimento, Emprego e Inovação'],
	['code' => 'SME', 'name' => 'Secretaria Municipal de Educação'],
	['code' => 'SMF', 'name' => 'Secretaria Municipal de Fazenda'],
	['code' => 'SMIH', 'name' => 'Secretaria Municipal de Infraestrutura e Habitação'],
	['code' => 'SEOP', 'name' => 'Secretaria Municipal de Ordem Pública'],
	['code' => 'SMS', 'name' => 'Secretaria Municipal de Saúde'],
	['code' => 'SMTR', 'name' => 'Secretaria Municipal de Transportes'],
	['code' => 'SMU', 'name' => 'Secretaria Municipal de Urbanismo'],
	['code' => 'CDURP', 'name' => 'Companhia de Desenvolvimento Urbano da Região do Porto do Rio de Janeiro'],
	['code' => 'CET-RIO', 'name' => 'Companhia de Engenharia de Tráfego do RJ'],
	['code' => 'RIOLUZ', 'name' => 'Companhia Municipal de Energia e Iluminação '],
	['code' => 'COMLURB', 'name' => 'Companhia Municipal de Limpeza Urbana'],
	['code' => 'RIOEVENTOS', 'name' => 'Rio Eventos Especiais'],
	['code' => 'RIOTUR', 'name' => 'Empresa de Turismo do Município do Rio de Janeiro'],
	['code' => 'RIOFILME', 'name' => 'Empresa Distribuidora de Filmes S.A.'],
	['code' => 'IC', 'name' => 'Empresa Municipal de Artes Gráficas - Imprensa da Cidade'],
	['code' => 'IPLANRIO', 'name' => 'Empresa Municipal de Informática'],
	['code' => 'MULTIRIO', 'name' => 'Empresa Municipal de Multimeios Ltda.'],
	['code' => 'RIO-URBE', 'name' => 'Empresa Municipal de Urbanização'],
	['code' => 'RIOSAÚDE', 'name' => 'Empresa Pública de Saúde do Rio de Janeiro'],
	['code' => 'GM-RIO', 'name' => 'Guarda Municipal do Rio de Janeiro'],
	['code' => 'PREVI-RIO', 'name' => 'Instituto de Previdência e Assistência'],
	['code' => 'IPP', 'name' => 'Instituto Municipal de Urbanismo Pereira Passos'],
	['code' => 'F-ARTES', 'name' => 'Fundação Cidade das Artes'],
	['code' => 'RIO-ÁGUAS', 'name' => 'Fundação Instituto das Águas do Município do Rio de Janeiro'],
	['code' => 'RIOZOO', 'name' => 'Fundação Jardim Zoológico da Cidade do Rio de Janeiro'],
	['code' => 'FPJ', 'name' => 'Fundação Parques e Jardins'],
	['code' => 'PLANETÁRIO', 'name' => 'Fundação Planetário da Cidade do Rio de Janeiro'],
	['code' => 'GEO-RIO', 'name' => 'Fundação Instituto de Geotécnica do Município do Rio de Janeiro'],
];